# Generated by Django 6.0.4 on 2026-05-06 17:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0003_useraccount_account_type_and_more'),
        ('sale', '0006_alter_invoice_number_lengths'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GSTEInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Ready', 'Ready'), ('Generated', 'Generated'), ('Cancelled', 'Cancelled'), ('Failed', 'Failed')], default='Draft', max_length=20)),
                ('irn', models.CharField(blank=True, max_length=64)),
                ('ack_no', models.CharField(blank=True, max_length=30)),
                ('ack_date', models.DateTimeField(blank=True, null=True)),
                ('signed_invoice', models.TextField(blank=True)),
                ('signed_qr_code', models.TextField(blank=True)),
                ('request_payload', models.JSONField(blank=True, default=dict)),
                ('response_payload', models.JSONField(blank=True, default=dict)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gst_e_invoice', to='sale.invoice')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gst_e_invoices', to='account.organization')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='GSTEWayBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Ready', 'Ready'), ('Generated', 'Generated'), ('Cancelled', 'Cancelled'), ('Failed', 'Failed')], default='Draft', max_length=20)),
                ('ewb_no', models.CharField(blank=True, max_length=20)),
                ('ewb_date', models.DateTimeField(blank=True, null=True)),
                ('valid_upto', models.DateTimeField(blank=True, null=True)),
                ('transporter_id', models.CharField(blank=True, max_length=15)),
                ('transporter_name', models.CharField(blank=True, max_length=120)),
                ('transport_mode', models.CharField(blank=True, max_length=10)),
                ('transport_doc_no', models.CharField(blank=True, max_length=30)),
                ('transport_doc_date', models.DateField(blank=True, null=True)),
                ('vehicle_no', models.CharField(blank=True, max_length=20)),
                ('distance_km', models.PositiveIntegerField(default=0)),
                ('request_payload', models.JSONField(blank=True, default=dict)),
                ('response_payload', models.JSONField(blank=True, default=dict)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gst_e_way_bill', to='sale.invoice')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gst_e_way_bills', to='account.organization')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='GSTReturnFiling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gstin', models.CharField(max_length=15)),
                ('return_type', models.CharField(choices=[('GSTR1', 'GSTR-1'), ('GSTR3B', 'GSTR-3B'), ('GSTR9', 'GSTR-9')], max_length=10)),
                ('period', models.CharField(help_text='MMYYYY for monthly returns, YYYY-YYYY for annual returns', max_length=20)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Ready', 'Ready'), ('Submitted', 'Submitted'), ('Filed', 'Filed'), ('Failed', 'Failed')], default='Draft', max_length=20)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('validation', models.JSONField(blank=True, default=dict)),
                ('provider', models.CharField(blank=True, max_length=30)),
                ('provider_reference', models.CharField(blank=True, max_length=120)),
                ('response_payload', models.JSONField(blank=True, default=dict)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gst_returns', to='account.organization')),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('organization', 'gstin', 'return_type', 'period')},
            },
        ),
        migrations.CreateModel(
            name='GSTIntegrationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(default='sandbox', max_length=30)),
                ('operation', models.CharField(max_length=80)),
                ('status', models.CharField(choices=[('Prepared', 'Prepared'), ('Sent', 'Sent'), ('Succeeded', 'Succeeded'), ('Failed', 'Failed')], default='Prepared', max_length=20)),
                ('endpoint', models.CharField(blank=True, max_length=255)),
                ('request_payload', models.JSONField(blank=True, default=dict)),
                ('response_payload', models.JSONField(blank=True, default=dict)),
                ('status_code', models.PositiveIntegerField(blank=True, null=True)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('e_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gst.gsteinvoice')),
                ('e_way_bill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gst.gstewaybill')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gst_integration_requests', to='account.organization')),
                ('return_filing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gst.gstreturnfiling')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TallyExport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gstin', models.CharField(blank=True, max_length=15)),
                ('export_type', models.CharField(choices=[('SalesVoucherXML', 'Sales Voucher XML')], default='SalesVoucherXML', max_length=30)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Generated', 'Generated'), ('Failed', 'Failed')], default='Generated', max_length=20)),
                ('filename', models.CharField(max_length=120)),
                ('content', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tally_exports', to='account.organization')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
