# Generated by Django 5.2.13 on 2026-04-28 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_bearer_token', models.CharField(help_text='Bearer token for API authentication', max_length=64)),
                ('is_active', models.BooleanField(default=True, help_text='Enable/disable API access')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'API Configuration',
                'verbose_name_plural': 'API Configuration',
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gstin', models.CharField(help_text='Valid 15-character GSTIN (e.g., 27AAAAA0000A1Z5)', max_length=15, unique=True)),
                ('name', models.CharField(help_text='Warehouse/Location name', max_length=200)),
                ('code', models.CharField(help_text='Short code for warehouse (e.g., WH-01, MUM-01)', max_length=10, unique=True)),
                ('legal_name', models.CharField(help_text='Legal name as per GST registration', max_length=200)),
                ('trade_name', models.CharField(blank=True, help_text='Trading name (if different from legal name)', max_length=200)),
                ('address', models.TextField(help_text='Complete registered address')),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('invoice_sequence', models.PositiveIntegerField(default=0, help_text='Current invoice number sequence for this location')),
                ('purchase_invoice_sequence', models.PositiveIntegerField(default=0, help_text='Current purchase invoice sequence')),
                ('is_default', models.BooleanField(default=False, help_text='Default warehouse for new transactions if no warehouse selected')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Warehouse',
                'verbose_name_plural': 'Warehouses',
                'ordering': ['name'],
            },
        ),
    ]
