# Generated by Django 5.2.13 on 2026-04-29 16:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0003_superadmintoken_apitoken_delete_apiconfiguration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='superadmintoken',
            name='name',
        ),
        migrations.AddField(
            model_name='superadmintoken',
            name='user',
            field=models.OneToOneField(blank=True, help_text='User must be a superuser', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='super_admin_token', to=settings.AUTH_USER_MODEL),
        ),
    ]
