# Generated by Django 6.0.4 on 2026-04-29 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0005_harden_token_storage'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='state',
            field=models.ForeignKey(blank=True, help_text='State of registration for GST purposes', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='warehouses', to='configuration.state'),
        ),
    ]
