# Generated by Django 5.2.13 on 2026-04-29 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='role',
            field=models.CharField(choices=[('Owner', 'Owner'), ('Admin', 'Admin'), ('Manager', 'Manager'), ('Sales', 'Sales'), ('Delivery', 'Delivery'), ('Warehouse', 'Warehouse'), ('Staff', 'Staff')], default='Staff', max_length=20),
        ),
    ]
