# Generated by Django 6.0.4 on 2026-04-29 20:35

import django.db.models.deletion
from django.db import migrations, models


def backfill_account_types(apps, schema_editor):
    UserAccount = apps.get_model('account', 'UserAccount')
    UserAccount.objects.filter(organization__isnull=False).update(account_type='org_user')


def noop_reverse(apps, schema_editor):
    return


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_useraccount_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='account_type',
            field=models.CharField(choices=[('ecommerce', 'Ecommerce'), ('org_user', 'Organization User'), ('super_admin', 'Super Admin')], default='ecommerce', max_length=20),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='account.organization'),
        ),
        migrations.RunPython(backfill_account_types, noop_reverse),
    ]
