# Generated by Django 5.2.13 on 2026-04-28 11:10

import django.db.models.deletion
import stock.models
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configuration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_bearer_token', models.CharField(max_length=64)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'API Configuration',
                'verbose_name_plural': 'API Configuration',
            },
        ),
        migrations.CreateModel(
            name='AttributeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='AttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50)),
                ('attribute_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='stock.attributetype')),
            ],
            options={
                'unique_together': {('attribute_type', 'value')},
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('sku', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('cgst_rate', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)),
                ('sgst_rate', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)),
                ('igst_rate', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)),
                ('has_variants', models.BooleanField(default=False)),
                ('current_stock', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, validators=[stock.models.validate_stock])),
                ('min_stock_level', models.PositiveIntegerField(default=0)),
                ('max_stock_level', models.PositiveIntegerField(default=0)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cost_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='stock.category')),
            ],
        ),
        migrations.CreateModel(
            name='ItemVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=50, unique=True)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cost_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('current_stock', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=12, validators=[stock.models.validate_stock])),
                ('is_active', models.BooleanField(default=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='stock.item')),
            ],
        ),
        migrations.CreateModel(
            name='ItemImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='items/')),
                ('is_primary', models.BooleanField(default=False)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='stock.item')),
                ('item_variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='stock.itemvariant')),
            ],
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(max_length=50, unique=True)),
                ('quantity_received', models.DecimalField(decimal_places=4, max_digits=12)),
                ('quantity_remaining', models.DecimalField(decimal_places=4, max_digits=12)),
                ('cost_per_unit', models.DecimalField(decimal_places=4, max_digits=12)),
                ('received_date', models.DateField()),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('item_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='stock.itemvariant')),
            ],
        ),
        migrations.CreateModel(
            name='OpeningStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=12)),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('as_of_date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opening_stocks', to='stock.item')),
                ('item_variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opening_stocks', to='stock.itemvariant')),
            ],
            options={
                'verbose_name': 'Opening Stock',
                'verbose_name_plural': 'Opening Stocks',
            },
        ),
        migrations.CreateModel(
            name='SerialNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Sold', 'Sold'), ('Return', 'Return'), ('Damaged', 'Damaged'), ('Lost', 'Lost')], default='Available', max_length=15)),
                ('purchase_date', models.DateTimeField(blank=True, null=True)),
                ('sale_date', models.DateTimeField(blank=True, null=True)),
                ('warranty_expiry', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='serial_numbers', to='stock.batch')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='serial_numbers', to='stock.item')),
                ('item_variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='serial_numbers', to='stock.itemvariant')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='serial_numbers', to='configuration.warehouse')),
            ],
            options={
                'verbose_name': 'Serial Number',
                'verbose_name_plural': 'Serial Numbers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('Purchase', 'Purchase'), ('Sale', 'Sale'), ('Adjustment', 'Adjustment'), ('Return', 'Return'), ('Damage', 'Damage')], max_length=15)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=12)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cgst_rate', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)),
                ('sgst_rate', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)),
                ('igst_rate', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reference_number', models.CharField(blank=True, max_length=50)),
                ('movement_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='stock.batch')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='stock.item')),
                ('item_variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='stock.itemvariant')),
            ],
        ),
        migrations.CreateModel(
            name='TaxCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code_type', models.CharField(choices=[('HSN', 'HSN'), ('SAC', 'SAC')], max_length=3)),
                ('code', models.CharField(max_length=10)),
                ('is_exempt', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'unique_together': {('code_type', 'code')},
            },
        ),
        migrations.AddField(
            model_name='item',
            name='tax_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='stock.taxcode'),
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('short_code', models.CharField(max_length=10)),
                ('conversion_factor', models.DecimalField(decimal_places=4, default=Decimal('1'), max_digits=10)),
                ('must_be_whole_number', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('target_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversions', to='stock.unit')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='stock.unit'),
        ),
        migrations.CreateModel(
            name='ItemVariantAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute_value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.attributevalue')),
                ('item_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='stock.itemvariant')),
            ],
            options={
                'unique_together': {('item_variant', 'attribute_value')},
            },
        ),
        migrations.CreateModel(
            name='TaxComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component', models.CharField(choices=[('CGST', 'CGST'), ('SGST', 'SGST'), ('IGST', 'IGST')], max_length=5)),
                ('rate', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)),
                ('tax_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='stock.taxcode')),
            ],
            options={
                'unique_together': {('tax_code', 'component')},
            },
        ),
    ]
