# Generated by Django 6.0.4 on 2026-04-26 15:34

import django.db.models.deletion
import stock.models
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttributeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='has_variants',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='current_stock',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, validators=[stock.models.validate_stock]),
        ),
        migrations.CreateModel(
            name='AttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50)),
                ('attribute_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='stock.attributetype')),
            ],
            options={
                'unique_together': {('attribute_type', 'value')},
            },
        ),
        migrations.CreateModel(
            name='ItemVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=50, unique=True)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cost_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('current_stock', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=12, validators=[stock.models.validate_stock])),
                ('is_active', models.BooleanField(default=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='stock.item')),
            ],
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(max_length=50, unique=True)),
                ('quantity_received', models.DecimalField(decimal_places=4, max_digits=12)),
                ('quantity_remaining', models.DecimalField(decimal_places=4, max_digits=12)),
                ('cost_per_unit', models.DecimalField(decimal_places=4, max_digits=12)),
                ('received_date', models.DateField()),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('item_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='stock.itemvariant')),
            ],
        ),
        migrations.CreateModel(
            name='ItemVariantAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute_value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.attributevalue')),
                ('item_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='stock.itemvariant')),
            ],
            options={
                'unique_together': {('item_variant', 'attribute_value')},
            },
        ),
    ]
