# Generated by Django 5.2.13 on 2026-04-29 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_attributetype_organization_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ApiConfiguration',
        ),
    ]
