# Generated by Django 6.0.4 on 2026-04-26 16:01

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_attributetype_item_has_variants_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='cgst_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5),
        ),
        migrations.AddField(
            model_name='item',
            name='igst_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5),
        ),
        migrations.AddField(
            model_name='item',
            name='sgst_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5),
        ),
        migrations.CreateModel(
            name='TaxCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code_type', models.CharField(choices=[('HSN', 'HSN'), ('SAC', 'SAC')], max_length=3)),
                ('code', models.CharField(max_length=10)),
                ('is_exempt', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'unique_together': {('code_type', 'code')},
            },
        ),
        migrations.AddField(
            model_name='item',
            name='tax_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='stock.taxcode'),
        ),
        migrations.CreateModel(
            name='TaxComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component', models.CharField(choices=[('CGST', 'CGST'), ('SGST', 'SGST'), ('IGST', 'IGST')], max_length=5)),
                ('rate', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)),
                ('tax_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='stock.taxcode')),
            ],
            options={
                'unique_together': {('tax_code', 'component')},
            },
        ),
    ]
