# Generated by Django 5.2.13 on 2026-04-30 23:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0006_warehouse_state'),
        ('stock', '0003_remove_apiconfiguration'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='requires_serial_tracking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='valuation_method',
            field=models.CharField(choices=[('FIFO', 'FIFO'), ('LIFO', 'LIFO')], default='FIFO', max_length=10),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='allocation_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='posted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='posting_state',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Posted', 'Posted'), ('Reversed', 'Reversed'), ('Failed', 'Failed')], default='Pending', max_length=10),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='serial_numbers',
            field=models.ManyToManyField(blank=True, related_name='stock_movements', to='stock.serialnumber'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='source_document_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='source_document_type',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='source_line_reference',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouse_stock_movements', to='configuration.warehouse'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('Opening', 'Opening'), ('Purchase', 'Purchase'), ('Sale', 'Sale'), ('Adjustment', 'Adjustment'), ('TransferIn', 'Transfer In'), ('TransferOut', 'Transfer Out'), ('Reserve', 'Reserve'), ('Release', 'Release'), ('Return', 'Return'), ('Damage', 'Damage')], max_length=15),
        ),
    ]
