# Generated by Django 6.0.4 on 2026-04-26 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_itemimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_bearer_token', models.CharField(max_length=64, unique=True)),
                ('token_created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'API Configuration',
                'verbose_name_plural': 'API Configuration',
            },
        ),
    ]
