# Generated by Django 6.0.4 on 2026-04-29 20:44

import commerce.models
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0003_useraccount_account_type_and_more'),
        ('configuration', '0006_warehouse_state'),
        ('stock', '0003_remove_apiconfiguration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('b2c', 'B2C'), ('b2b', 'B2B'), ('marketplace', 'Marketplace')], default='b2c', max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('checked_out', 'Checked Out'), ('abandoned', 'Abandoned')], default='open', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('sub_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('grand_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('checked_out_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commerce_carts', to='account.useraccount')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='CommerceListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('compare_at_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('min_quantity', models.DecimalField(decimal_places=4, default=Decimal('1'), max_digits=12, validators=[commerce.models.validate_positive_quantity])),
                ('max_quantity', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_b2c_enabled', models.BooleanField(default=True)),
                ('is_b2b_enabled', models.BooleanField(default=True)),
                ('is_marketplace_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commerce_listings', to='stock.item')),
                ('item_variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commerce_listings', to='stock.itemvariant')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commerce_listings', to='account.organization')),
            ],
            options={
                'verbose_name': 'Commerce Listing',
                'verbose_name_plural': 'Commerce Listings',
                'ordering': ['title', 'id'],
                'unique_together': {('organization', 'item', 'item_variant')},
            },
        ),
        migrations.CreateModel(
            name='CommerceOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=30, unique=True)),
                ('channel', models.CharField(choices=[('b2c', 'B2C'), ('b2b', 'B2B'), ('marketplace', 'Marketplace')], default='b2c', max_length=20)),
                ('status', models.CharField(choices=[('placed', 'Placed'), ('cancelled', 'Cancelled')], default='placed', max_length=20)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('fulfillment_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('billing_snapshot', models.JSONField(default=dict)),
                ('shipping_snapshot', models.JSONField(default=dict)),
                ('notes', models.TextField(blank=True)),
                ('sub_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('grand_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('placed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commerce_orders', to='account.useraccount')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommerceOrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('sku', models.CharField(max_length=50)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=12)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commerce_order_lines', to='stock.item')),
                ('item_variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commerce_order_lines', to='stock.itemvariant')),
                ('listing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_lines', to='commerce.commercelisting')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='commerce.commerceorder')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commerce_order_lines', to='account.organization')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ShopperAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('recipient_name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('line1', models.CharField(max_length=255)),
                ('line2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
                ('country', models.CharField(default='India', max_length=100)),
                ('is_default_shipping', models.BooleanField(default=False)),
                ('is_default_billing', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shopper_addresses', to='configuration.state')),
                ('user_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopper_addresses', to='account.useraccount')),
            ],
            options={
                'verbose_name': 'Shopper Address',
                'verbose_name_plural': 'Shopper Addresses',
                'ordering': ['-is_default_shipping', '-is_default_billing', '-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='commerceorder',
            name='billing_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_orders', to='commerce.shopperaddress'),
        ),
        migrations.AddField(
            model_name='commerceorder',
            name='shipping_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipping_orders', to='commerce.shopperaddress'),
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=4, default=Decimal('1'), max_digits=12, validators=[commerce.models.validate_positive_quantity])),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('line_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='commerce.cart')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='commerce.commercelisting')),
            ],
            options={
                'ordering': ['created_at', 'id'],
                'unique_together': {('cart', 'listing')},
            },
        ),
    ]
