# Generated by Django 6.0.4 on 2026-04-29 21:19

import commerce.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_useraccount_account_type_and_more'),
        ('commerce', '0001_initial'),
        ('stock', '0003_remove_apiconfiguration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommerceAuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=80)),
                ('entity_type', models.CharField(max_length=120)),
                ('entity_id', models.CharField(blank=True, max_length=50)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commerce_audit_events', to='account.useraccount')),
                ('actor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commerce_audit_events', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commerce_audit_events', to='account.organization')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommerceNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField(blank=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commerce_notifications', to='account.organization')),
                ('user_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commerce_notifications', to='account.useraccount')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommerceReturnRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=12, validators=[commerce.models.validate_positive_quantity])),
                ('reason', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('approved', 'Approved'), ('received', 'Received'), ('processed', 'Processed'), ('rejected', 'Rejected'), ('closed', 'Closed')], default='requested', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_requests', to='commerce.commerceorder')),
                ('order_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_requests', to='commerce.commerceorderline')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commerce_return_requests', to='account.organization')),
            ],
            options={
                'ordering': ['-requested_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CommerceRefund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('processed', 'Processed'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='commerce.commerceorder')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commerce_refunds', to='account.organization')),
                ('return_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='refund', to='commerce.commercereturnrequest')),
            ],
            options={
                'ordering': ['-created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CommerceSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reserve_stock_on_checkout', models.BooleanField(default=True)),
                ('prevent_oversell', models.BooleanField(default=True)),
                ('manual_fulfillment', models.BooleanField(default=True)),
                ('manual_returns_only', models.BooleanField(default=True)),
                ('allow_b2b_price_overrides', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='commerce_settings', to='account.organization')),
            ],
            options={
                'verbose_name': 'Commerce Settings',
                'verbose_name_plural': 'Commerce Settings',
            },
        ),
        migrations.CreateModel(
            name='CommerceShipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('manual', 'Manual'), ('integrated', 'Integrated')], default='manual', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('packed', 'Packed'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('carrier_name', models.CharField(blank=True, max_length=120)),
                ('tracking_number', models.CharField(blank=True, max_length=120)),
                ('shipped_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shipment', to='commerce.commerceorder')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commerce_shipments', to='account.organization')),
            ],
            options={
                'ordering': ['-created_at', 'id'],
            },
        ),
        migrations.AddField(
            model_name='commercereturnrequest',
            name='shipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_requests', to='commerce.commerceshipment'),
        ),
        migrations.CreateModel(
            name='InventoryReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=12, validators=[commerce.models.validate_positive_quantity])),
                ('status', models.CharField(choices=[('reserved', 'Reserved'), ('released', 'Released'), ('consumed', 'Consumed'), ('expired', 'Expired')], default='reserved', max_length=20)),
                ('reserved_at', models.DateTimeField(auto_now_add=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commerce_reservations', to='stock.item')),
                ('item_variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commerce_reservations', to='stock.itemvariant')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='commerce.commercelisting')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='commerce.commerceorder')),
                ('order_line', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reservation', to='commerce.commerceorderline')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commerce_reservations', to='account.organization')),
            ],
            options={
                'ordering': ['-reserved_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('b2c', 'B2C'), ('b2b', 'B2B'), ('marketplace', 'Marketplace')], default='b2c', max_length=20)),
                ('name', models.CharField(default='Wishlist', max_length=120)),
                ('is_default', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlists', to='account.useraccount')),
            ],
            options={
                'ordering': ['-is_default', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='CommerceContentPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=120)),
                ('title', models.CharField(max_length=200)),
                ('page_type', models.CharField(choices=[('home', 'Home'), ('about', 'About'), ('policy', 'Policy'), ('faq', 'FAQ'), ('category', 'Category'), ('custom', 'Custom')], default='custom', max_length=20)),
                ('body', models.TextField(blank=True)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commerce_pages', to='account.organization')),
            ],
            options={
                'ordering': ['title'],
                'unique_together': {('organization', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='CommercePriceOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer_organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commerce_buyer_price_overrides', to='account.organization')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_overrides', to='commerce.commercelisting')),
                ('seller_organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commerce_price_overrides', to='account.organization')),
            ],
            options={
                'ordering': ['listing__title', 'buyer_organization__name'],
                'unique_together': {('seller_organization', 'buyer_organization', 'listing')},
            },
        ),
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('title', models.CharField(blank=True, max_length=200)),
                ('body', models.TextField(blank=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='commerce.commercelisting')),
                ('user_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_reviews', to='account.useraccount')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('listing', 'user_account')},
            },
        ),
        migrations.CreateModel(
            name='WishlistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist_items', to='commerce.commercelisting')),
                ('wishlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='commerce.wishlist')),
            ],
            options={
                'ordering': ['created_at', 'id'],
                'unique_together': {('wishlist', 'listing')},
            },
        ),
    ]
