# Generated by Django 6.0.4 on 2026-04-29 21:28

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_useraccount_account_type_and_more'),
        ('commerce', '0002_commerceauditevent_commercenotification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commercesettings',
            name='marketplace_commission_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))]),
        ),
        migrations.CreateModel(
            name='MarketplaceSettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gross_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('commission_rate', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)),
                ('commission_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('adjustment_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('net_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('ready', 'Ready'), ('paid', 'Paid'), ('cancelled', 'Cancelled'), ('reversed', 'Reversed')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('ready_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('reversed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketplace_settlements', to='commerce.commerceorder')),
                ('seller_organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketplace_settlements', to='account.organization')),
            ],
            options={
                'ordering': ['-created_at', 'id'],
                'unique_together': {('order', 'seller_organization')},
            },
        ),
        migrations.CreateModel(
            name='MarketplacePayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('method', models.CharField(choices=[('manual', 'Manual'), ('gateway', 'Gateway'), ('bank', 'Bank Transfer')], default='manual', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processed', 'Processed'), ('failed', 'Failed'), ('reversed', 'Reversed')], default='pending', max_length=20)),
                ('provider_name', models.CharField(blank=True, max_length=120)),
                ('provider_reference', models.CharField(blank=True, max_length=120)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('settlement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payout', to='commerce.marketplacesettlement')),
            ],
            options={
                'ordering': ['-created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MarketplaceSettlementLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=12)),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('commission_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('order_line', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='marketplace_settlement_line', to='commerce.commerceorderline')),
                ('settlement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='commerce.marketplacesettlement')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
