# Generated by Django 5.2.13 on 2026-04-28 11:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configuration', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_number', models.CharField(help_text='Auto-generated shift number', max_length=20, unique=True)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed')], default='Open', max_length=10)),
                ('opening_cash', models.DecimalField(decimal_places=2, help_text='Cash in drawer at shift start', max_digits=12)),
                ('closing_cash', models.DecimalField(blank=True, decimal_places=2, help_text='Cash in drawer at shift end', max_digits=12, null=True)),
                ('expected_cash', models.DecimalField(blank=True, decimal_places=2, help_text='Expected cash based on transactions', max_digits=12, null=True)),
                ('variance', models.DecimalField(blank=True, decimal_places=2, help_text='Difference between closing and expected cash', max_digits=12, null=True)),
                ('opening_time', models.DateTimeField(auto_now_add=True, help_text='When shift was opened')),
                ('closing_time', models.DateTimeField(blank=True, help_text='When shift was closed', null=True)),
                ('notes', models.TextField(blank=True, help_text='Notes for this shift')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='Cashier/user for this shift', on_delete=django.db.models.deletion.PROTECT, related_name='shifts', to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(help_text='Warehouse/location for this shift', on_delete=django.db.models.deletion.PROTECT, related_name='shifts', to='configuration.warehouse')),
            ],
            options={
                'verbose_name': 'Shift',
                'verbose_name_plural': 'Shifts',
                'ordering': ['-opening_time'],
            },
        ),
        migrations.CreateModel(
            name='CashTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('CashIn', 'Cash In'), ('CashOut', 'Cash Out')], help_text='Type of cash transaction', max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Transaction amount', max_digits=12)),
                ('reason', models.CharField(help_text='Reason for transaction', max_length=200)),
                ('reference', models.CharField(blank=True, help_text='Reference number (e.g., bank receipt)', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_transactions', to=settings.AUTH_USER_MODEL)),
                ('shift', models.ForeignKey(help_text='Shift this transaction belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='pos.shift')),
            ],
            options={
                'verbose_name': 'Cash Transaction',
                'verbose_name_plural': 'Cash Transactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
