# Generated by Django 5.2.13 on 2026-04-30 23:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0003_useraccount_account_type_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trace_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('correlation_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('event_type', models.CharField(db_index=True, max_length=120)),
                ('action', models.CharField(blank=True, default='', max_length=120)),
                ('source_app', models.CharField(blank=True, default='', max_length=50)),
                ('request_method', models.CharField(blank=True, default='', max_length=10)),
                ('request_path', models.CharField(blank=True, default='', max_length=255)),
                ('request_query', models.TextField(blank=True, default='')),
                ('status_code', models.PositiveIntegerField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=512)),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('object_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('object_repr', models.CharField(blank=True, default='', max_length=255)),
                ('before_state', models.JSONField(blank=True, default=dict)),
                ('after_state', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('outcome', models.CharField(choices=[('success', 'Success'), ('failure', 'Failure')], default='success', max_length=20)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='account.useraccount')),
                ('actor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='contenttypes.contenttype')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='account.organization')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='AuditEventLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_type', models.CharField(choices=[('primary', 'Primary'), ('related', 'Related'), ('source', 'Source'), ('request', 'Request')], default='related', max_length=20)),
                ('object_id', models.CharField(db_index=True, max_length=64)),
                ('object_repr', models.CharField(blank=True, default='', max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='audit.auditevent')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['trace_id', 'created_at'], name='audit_audit_trace_i_fced6a_idx'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['correlation_id', 'created_at'], name='audit_audit_correla_f07ac9_idx'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['organization', 'created_at'], name='audit_audit_organiz_4fc53a_idx'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['actor_user', 'created_at'], name='audit_audit_actor_u_086bd4_idx'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['event_type', 'created_at'], name='audit_audit_event_t_124af2_idx'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['content_type', 'object_id'], name='audit_audit_content_c1f818_idx'),
        ),
        migrations.AddIndex(
            model_name='auditeventlink',
            index=models.Index(fields=['content_type', 'object_id'], name='audit_audit_content_effc62_idx'),
        ),
        migrations.AddIndex(
            model_name='auditeventlink',
            index=models.Index(fields=['relation_type'], name='audit_audit_relatio_4085ab_idx'),
        ),
    ]
