# Generated by Django 5.2.13 on 2026-04-29 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('configuration', '0002_apiconfiguration_organization_warehouse_organization_and_more'),
        ('sale', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodreceiptnote',
            name='business_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grns', to='configuration.warehouse'),
        ),
        migrations.AlterField(
            model_name='paymentout',
            name='business_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments_out', to='configuration.warehouse'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='business_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='configuration.warehouse'),
        ),
        migrations.AlterField(
            model_name='order',
            name='business_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='configuration.warehouse'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='business_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='configuration.warehouse'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='business_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='configuration.warehouse'),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='business_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_invoices', to='configuration.warehouse'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='billing_state',
            field=models.ForeignKey(help_text='Place of supply (customer state)', on_delete=django.db.models.deletion.PROTECT, related_name='invoices_billed', to='configuration.state'),
        ),
        migrations.AlterField(
            model_name='party',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='parties', to='configuration.state'),
        ),
        migrations.AddField(
            model_name='party',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='account.organization'),
        ),
        migrations.DeleteModel(
            name='BusinessLocation',
        ),
        migrations.DeleteModel(
            name='State',
        ),
    ]
