# Generated by Django 5.2.13 on 2026-05-01 00:10

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_useraccount_account_type_and_more'),
        ('configuration', '0006_warehouse_state'),
        ('sale', '0003_pricelist_pricelistitem_quotation_quotationitem'),
        ('stock', '0004_item_requires_serial_tracking_item_valuation_method_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='gross_profit_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12),
        ),
        migrations.AddField(
            model_name='invoice',
            name='tcs_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12),
        ),
        migrations.AddField(
            model_name='invoice',
            name='tcs_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='cost_basis',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='cost_price_snapshot',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='gross_profit',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12),
        ),
        migrations.CreateModel(
            name='DeliveryChallan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challan_number', models.CharField(max_length=20, unique=True)),
                ('challan_date', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Dispatched', 'Dispatched'), ('Invoiced', 'Invoiced'), ('Cancelled', 'Cancelled')], default='Draft', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_challans', to='configuration.warehouse')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_challans_created', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_challans', to='account.organization')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_challans', to='sale.party')),
            ],
            options={
                'verbose_name': 'Delivery Challan',
                'verbose_name_plural': 'Delivery Challans',
                'ordering': ['-challan_date', '-id'],
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='source_challans',
            field=models.ManyToManyField(blank=True, related_name='invoices', to='sale.deliverychallan'),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='source_challan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_items', to='sale.deliverychallan'),
        ),
        migrations.CreateModel(
            name='DeliveryChallanItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hsn_code', models.CharField(blank=True, max_length=10)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=12)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=12)),
                ('discount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('delivery_challan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sale.deliverychallan')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_challan_items', to='stock.item')),
                ('item_variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_challan_items', to='stock.itemvariant')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_challan_items', to='stock.unit')),
            ],
            options={
                'verbose_name': 'Delivery Challan Item',
                'verbose_name_plural': 'Delivery Challan Items',
            },
        ),
    ]
