# Generated by Django 5.2.13 on 2026-05-01 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0004_invoice_gross_profit_amount_invoice_tcs_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodreceiptnote',
            name='posted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='goodreceiptnote',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Posted', 'Posted'), ('Cancelled', 'Cancelled')], default='Draft', max_length=20),
        ),
    ]
