# Generated by Django 5.2.13 on 2026-05-02 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_useraccount_account_type_and_more'),
        ('accounting', '0002_expense'),
        ('sale', '0006_alter_invoice_number_lengths'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('bank_name', models.CharField(max_length=200)),
                ('branch_name', models.CharField(blank=True, max_length=200)),
                ('account_number', models.CharField(max_length=34)),
                ('ifsc_code', models.CharField(blank=True, max_length=11)),
                ('account_type', models.CharField(choices=[('Current', 'Current'), ('Savings', 'Savings'), ('Cash Credit', 'Cash Credit'), ('Overdraft', 'Overdraft'), ('Other', 'Other')], default='Current', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='account.organization')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('organization', 'account_number')},
            },
        ),
        migrations.CreateModel(
            name='ChequeTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cheque_number', models.CharField(max_length=50)),
                ('cheque_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('transaction_type', models.CharField(choices=[('Issued', 'Issued'), ('Received', 'Received')], default='Issued', max_length=20)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Deposited', 'Deposited'), ('Cleared', 'Cleared'), ('Bounced', 'Bounced'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20)),
                ('deposited_at', models.DateTimeField(blank=True, null=True)),
                ('cleared_at', models.DateTimeField(blank=True, null=True)),
                ('bounced_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cheques', to='accounting.bankaccount')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cheque_transactions', to='account.organization')),
                ('party', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cheque_transactions', to='sale.party')),
            ],
            options={
                'ordering': ['-cheque_date', '-id'],
                'unique_together': {('organization', 'cheque_number')},
            },
        ),
    ]
